name: QA Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Check files exist
        run: |
          echo "Checking required files..."
          test -f README.md && echo "Success README.md exists" || echo "Exception README.md missing"
          test -f checklist.md && echo "Success checklist.md exists" || echo "Exception checklist.md missing"
          test -f bug-reports.md && echo "Succes bug-reports.md exists" || echo "Exception bug-reports.md missing"
          test -f Demoblaze.postman_collection.json && echo "Succes Demoblaze.postman_collection.json exists" || echo "Exception Demoblaze.postman_collection.json missing"
          echo "All checks completed!"
